### ISSUE TITLE
Respect CIDR range specification?

### ISSUE THREAD

**Issue by Skarlett** [magiclen/cidr-utils#6]
Input: 0.0.0.5/24 
Outputs: 0.0.0.0, 0.0.0.1, 0.0.0.2
----
Expected output: `0.0.0.5, 0.0.0.6, ... 0.0.0.255`

**Comment by magiclen** [comment]
Why `0.0.0.5/24` starts with `0.0.0.5`?

**Comment by Skarlett** [comment]
`0.0.0.X/24` where X is the start of the CIDR range. This should be explicit instead of implicitly the being of the netmask range since the information is overwritten once converted into `IpCidr`
